apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  mongo-init.js: |
    db = db.getSiblingDB('calculator');
    db.createUser({
      user: "admin",
      pwd: "admin123",
      roles: [{ role: "readWrite", db: "calculator" }]
    });
